name: "Install Python and Poetry"
description: "Setup Python and Poetry"

inputs:
  workdir:
    description: "The working directory"
    required: false
    default: "."
  install-deps:
    description: "Should the action install deps?"
    required: false
    default: false
  only-dev-deps:
    description: "Should the action only install the dev dependencies?"
    required: false
    default: false
  cache:
    description: "Should the action try to cache the poetry dependencies?"
    required: false
    default: true

outputs:
  python-version:
    description: "The installed Python version"
    # works for cache OR non-cached step!
    value: ${{ steps.setup_python_no_cache.outputs.python-version || steps.setup_python_cache.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Set Poetry Version
      run: |
        if [ -f .poetry-version ]; then
          echo "POETRY_VERSION=$(cat .poetry-version)" >> $GITHUB_ENV
        else
          echo ".poetry-version file not found. Aborting." >&2
          exit 1
        fi
      shell: bash

    - name: Check .python-version file
      run: |
        if [ -f .python-version ]; then
          echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
        else
          echo ".python-version file not found. Aborting." >&2
          exit 1
        fi
      shell: bash

    - name: Install Poetry ${{ env.POETRY_VERSION }}
      run: |
        curl -sSL ${{ env.POETRY_URL }} | \
          python - --version ${{ env.POETRY_VERSION }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
      env:
        POETRY_URL: https://install.python-poetry.org

    - name: Set up Python ${{ inputs.python-version }} (cache)
      if: ${{ inputs.cache == 'true' }}
      id: setup_python_cache
      uses: actions/setup-python@v4
      with:
        python-version-file: "${{ inputs.workdir }}/.python-version"
        cache: "poetry" # This line enables caching for Python dependencies that are managed by Poetry, speeding up build times

    - name: Set up Python ${{ inputs.python-version }} (no-cache)
      if: ${{ inputs.cache == 'false' }}
      id: setup_python_no_cache
      uses: actions/setup-python@v4
      with:
        python-version-file: "${{ inputs.workdir }}/.python-version"

    - name: Install Dev Dependencies
      # Only installs dev dependencies
      if: ${{ inputs.install-deps == 'true' && inputs.only-dev-deps == 'true'}}
      run: cd ${{ inputs.workdir }} && poetry install --only dev
      shell: bash

    - name: Install Project Dependencies
      # Installs regular dependencies AND dev dependencies
      if: ${{ inputs.install-deps == 'true' && inputs.only-dev-deps == 'false'}}
      run: cd ${{ inputs.workdir }} && poetry install
      shell: bash
